name: Trigger Workflow in Other Repo

# on:
  # push:
    # branches:
      # - main  # Trigger on pushes to main branch

on:
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source repository
        uses: actions/checkout@v3


      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone destination repository
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/Raamasaamy/TestPipe.git destination-repo

      - name: Copy specific files to destination repo
        run: |
          #Remove the folder, if alreay exists.
          if [ -d destination-repo/assets ]; then
            rm -rf destination-repo/assets
            echo "Directory removed."
          else
            echo "Directory does not exist."
          fi
          
          cp -r ./assets destination-repo/
          # cp ./assets/entitlements/* destination-repo/assets/entitlements/
          
          cd destination-repo
          git add .
          git commit -m "Copied specific files from source repo"
          git push origin main

      - name: Trigger Workflow in TestPipe Repository
        run: |
          REPO_OWNER="Raamasaamy2025"
          REPO_NAME="TestPipe"
          WORKFLOW_ID="CodeSign.yml"  # Filename of workflow in repo B
          GITHUB_TOKEN="${{ secrets.TARGET_REPO_PAT }}"  # This repository secret

          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{
              "ref": "main",
              "inputs": {
                "ipa_path": "'"./assets/Remote.ipa"'",
                "certificate_name": "'"iPhone Distribution: Robert Bosch GmbH (JRH3BDU5ZX)"'",
                "main_new_bundle_id": "'"com.bosch.prod.remotefiresafety"'",
                "main_entitlements_plist_path": "'"./assets/entitlements/entitlements.plist"'",
                "output_ipa_path": "'"./output"'",
                "extension_entitlements_plist_dir": "'"./assets/entitlements/extensions"'",
                "extension_provisioning_profile_dir": "'""'"
              }
            }' \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_ID/dispatches"
